### ISSUE TITLE
[Suggestion] ~WE routed so that flashing from the Breadbin works

### ISSUE THREAD

**Issue by bastetfurry** [msolajic/c64-uni-cart#3]
A little suggestion for a next revision if you are going to make one.

My hubby has ordered a bunch of 512kByte flash from Reichelt yesterday and i was looking into writing to them from the Breadbin, studying the board and the shematic just to find out that the Write Enable line is not routed in any way or jumper configuration to the Read/Write line of the C64s cart port.

Could you route the Read/Write line to the flashes Write Enable line trough some selectable jumper, enabling onboard flashing?

**Comment by msolajic** [comment]
Yes, I can look into that (if there's a way to route it, because it's already pretty dense). I wasn't thinking about flashing the cartridge from the C64, because the cartridge image generation is done on the PC side, and from my experience with EasyFlash it can be very slow.
