### ISSUE TITLE
Bin Prince of Persia

### ISSUE THREAD

**Issue by fbugallo** [msolajic/c64-uni-cart#4]
I can't / understood how to generate the Bin file from the Prince of Persia. I follow the instructions but my knowledge is poor and I cannot advance. Buy your PCBs at PCBWay. Could you help me please??

**Comment by msolajic** [comment]
Hi, I chose not to share the pached files publicly, because I didn't want to upset the developers or original creators. That's why I shared the instructions and patch files. Anyway, drop me an e-mail (same username at gmail), and I'll send you the patched file.
